services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - blog-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongodb
    networks:
      - blog-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-app
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/blog
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_TRUST_HOST=true
      - GCS_PROJECT_ID=${GCS_PROJECT_ID}
      - GCS_CLIENT_EMAIL=${GCS_CLIENT_EMAIL}
      - GCS_PRIVATE_KEY=${GCS_PRIVATE_KEY}
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge

volumes:
  mongodb_data:
